name: Release Zed Extension

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Bump Zed Extension
    runs-on: ubuntu-latest
    steps:
      - uses: huacnlee/zed-extension-action@v2
        with:
          extension-name: markdown-pdf
          push-to: matinfo/zed-extensions
        env:
          # Personal Access Token with "repo" and "workflow" scopes
          # Add it in: Settings → Secrets and variables → Actions → New repository secret
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
